### ISSUE TITLE
[Request] Active Directory transition - browser bug fix documentation

### ISSUE THREAD

**Issue by yoderj** [gagandaroach/rosie#10]
When a user switches from a old native linux login to their ad.msoe.edu (active directory) login, they may experience trouble with their browser partly remembering their old login.

If you wish, save this documentation somewhere where users might find it who are struggling with the transition:

https://stackoverflow.com/c/msoe/q/87/2

**Comment by gagandaroach** [comment]
Closing issue, AD sync disabled on cluster. Logout button fix made logging out typically work. 

**Future Readers**
If logging out does not work on your browser, the above MSOE stackoverflow topic may help.
